CONFIG_FULL_NAME  = loadOrder.CONFIG_FULL_NAME
CONFIG_SHORT_NAME = loadOrder.CONFIG_SHORT_NAME
CONFIG_PATH       = loadOrder.CONFIG_PATH
CONFIG_VERSION    = loadOrder.CONFIG_VERSION
SHORT_NAME        = loadOrder.SHORT_NAME
FULL_NAME         = loadOrder.FULL_NAME
VARIABLE_NAME     = loadOrder.VARIABLE_NAME

loadOrder.FILES['package.js'] = """
  this.#{VARIABLE_NAME} = {};

  var exists      = Npm.require('fs').existsSync;
  var pathResolve = Npm.require('path').resolve;

  var sourceExists = function(source) {
    return exists(pathResolve('#{CONFIG_PATH}', source));
  };

  Package.describe({
    name    : '#{CONFIG_FULL_NAME}',
    version : '#{CONFIG_VERSION}',
    summary : 'This package is automatically generated by #{FULL_NAME}',
  });

  Package.registerBuildPlugin({
    name: '#{SHORT_NAME}',
    npmDependencies: {
      'glob'   : '5.0.5',
      'mkdirp' : '0.5.0',
      'rimraf' : '2.3.2'
    },
    use: [ 'coffeescript@1.0.6' ],
    sources: [
        '#{CONFIG_SHORT_NAME}.js',
        '#{CONFIG_SHORT_NAME}.coffee',
        '#{SHORT_NAME}.min.js'
      ].filter(function(source) {
        return sourceExists(source);
      })
  });

  """
